"""Api initial migration file."""
# Generated by Django 3.2.1 on 2021-06-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):  # noqa: D101

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='key')),  # noqa: E501
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),  # noqa: E501
                ('director', models.CharField(blank=True, max_length=50, verbose_name='director')),  # noqa: E501
                ('producer', models.CharField(blank=True, max_length=50, verbose_name='producer')),  # noqa: E501
                ('release_date', models.PositiveIntegerField(blank=True, null=True, verbose_name='release_date')),  # noqa: E501
                ('created_at', models.DateField(auto_now_add=True, help_text='the date when movie was created', verbose_name='created_at')),  # noqa: E501
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='key')),  # noqa: E501
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),  # noqa: E501
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='gender')),  # noqa: E501
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='age')),  # noqa: E501
                ('created_at', models.DateField(auto_now_add=True, help_text='the date when people was created', verbose_name='created_at')),  # noqa: E501
                ('movies', models.ManyToManyField(related_name='people', to='api.Movie')),  # noqa: E501
            ],
            options={
                'verbose_name': 'people',
                'verbose_name_plural': 'people',
            },
        ),
    ]
