# Generated by Django 3.2.1 on 2021-06-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='key')),
                ('title', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='title')),
                ('director', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='director')),
                ('producer', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='producer')),
                ('release_date', models.PositiveIntegerField(blank=True, null=True, verbose_name='release_date')),
                ('created_at', models.DateField(auto_now_add=True, help_text='the date when movie was created', verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='key')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='name')),
                ('gender', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='gender')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='age')),
                ('created_at', models.DateField(auto_now_add=True, help_text='the date when people was created', verbose_name='created_at')),
                ('movies', models.ManyToManyField(related_name='people', to='api.Movie')),
            ],
            options={
                'verbose_name': 'people',
                'verbose_name_plural': 'people',
            },
        ),
    ]
