# Generated by Django 3.2.1 on 2021-06-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='people',
            name='key',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='key'),
        ),
    ]
